## Namespace
namespace: default
cloudProvider: aws
AWS_SSL_ARN: arn:aws:acm...
domain: segmentanythingservice.com
serviceType: ClusterIP
adminEmail: admin@segmentanythingservice.com
# ====================================================
# encoder gpu-9f21a4918e0ead256221e0524a9ebefe7ddcc55b
# ====================================================
encoder:
  enabled: true
  replicas: 1
  serviceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
  image:
    name: 685980093638.dkr.ecr.us-east-1.amazonaws.com/sam-service
    tag: gpu-9f21a4918e0ead256221e0524a9ebefe7ddcc55b
  env:
    GitSha: 9f21a4918e0ead256221e0524a9ebefe7ddcc55b
  persistenceDisk:
    enabled: false
    AWS_ElasticBlockStore_volumeID: vol-0888a8922504d118a
    AWS_ElasticBlockStore_size: 50Gi
    MODEL_DIR: /home/model-server/volume
  nodeSelector:
    enabled: true
    label_key: nodegroup_type
    label_value: g4dn-xlarge-ondemand
# ====================================================
# decoder
# ====================================================
decoder:
  enabled: true
  replicas: 1
  serviceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
  image:
    name: 685980093638.dkr.ecr.us-east-1.amazonaws.com/sam-service
    tag: cpu-9f21a4918e0ead256221e0524a9ebefe7ddcc55b
  env:
    GitSha: 9f21a4918e0ead256221e0524a9ebefe7ddcc55b
  persistenceDisk:
    enabled: false
    AWS_ElasticBlockStore_volumeID: vol-084afed32a29fdc9a
    AWS_ElasticBlockStore_size: 50Gi
    MODEL_DIR: /home/model-server/volume
  nodeSelector:
    enabled: true
    label_key: nodegroup_type
    label_value: cpu-worker-ondemand
